### ISSUE TITLE
Error running the project following the instructions

### ISSUE THREAD

**Issue by orenelbaum** [gpoesia/certified-reasoning#1]
I followed the instructions on Linux (WSL) and got the following error:
```
~/stuff/certified-reasoning/learning$ python3 lm_tool.py
Traceback (most recent call last):
  File "lm_tool.py", line 23, in <module>
    import domain
  File "/home/oren/stuff/certified-reasoning/learning/domain.py", line 17, in <module>
    from util import choose_from_list, parse_sexp, format_sexp, randomize_atoms
  File "/home/oren/stuff/certified-reasoning/learning/util.py", line 43, in <module>
    def encode_batch(b: list[str], device: torch.device, bos=True, eos=True) -> torch.LongTensor:
TypeError: 'type' object is not subscriptable
```

Also Tiktoken is missing from requirements.txt, I had to add it.

**Comment by orenelbaum** [comment]
My bad, I was using an old Python version (I'm a Python noob).
Now I'm getting this
```
~/stuff/certified-reasoning/learning$ python3 lm_tool.py
Traceback (most recent call last):
  File "/home/oren/stuff/certified-reasoning/learning/lm_tool.py", line 24, in <module>
    import tactics
  File "/home/oren/stuff/certified-reasoning/learning/tactics.py", line 16, in <module>
    from policy import Episode
ModuleNotFoundError: No module named 'policy'
```

Edit: I removed the tactics import and it works! Also had to install openai and lark.

**Comment by gpoesia** [comment]
Thanks for the PRs! I'll leave this open for a few days just in case you hit anything else. Feel free to post here if so!
